version: '3.9'
services:
  api:
    build: .
    container_name: vitalispulse_api
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16
    container_name: vitalispulse_postgres
    restart: always
    environment:
      POSTGRES_USER: vitalispulse
      POSTGRES_PASSWORD: vitalispulse
      POSTGRES_DB: vitalispulse_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vitalispulse_redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: vitalispulse_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mailhog:
    image: mailhog/mailhog
    container_name: vitalispulse_mailhog
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

volumes:
  pgdata:
